# Generated by Django 4.1.3 on 2022-12-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.IntegerField(choices=[(1, 'League Season'), (2, 'Cup')], max_length=30),
        ),
    ]
