# Generated by Django 4.1.3 on 2022-12-08 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('competitions', '0004_alter_competition_competition_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.IntegerField(choices=[(2, 'Cup'), (1, 'League Season')]),
        ),
        migrations.AlterField(
            model_name='playerinteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
