# Generated by Django 4.1.3 on 2022-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_competition_type_alter_match_away_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='type',
            field=models.IntegerField(choices=[(1, 'League Season'), (2, 'Cup')]),
        ),
    ]
