# Generated by Django 4.1.3 on 2022-12-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_alter_competition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='type',
        ),
    ]
