# Generated by Django 4.1.3 on 2022-12-13 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_date_of_birth'),
        ('teams', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0009_remove_competition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nazwa Rozgrywek'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Właściciel'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(to='teams.team', verbose_name='Uczestnicy'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_goal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gości'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_away', to='teams.team', verbose_name='Drużyna gości'),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='Rozgrywki'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_goal',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bramki gospodarzy'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='teams.team', verbose_name='Drużyna gospodarzy'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data meczu'),
        ),
        migrations.AlterField(
            model_name='playerinteam',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Nazwa zawodnika:'),
        ),
        migrations.AlterField(
            model_name='playerinteam',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='W rozgrywkach:'),
        ),
        migrations.AlterField(
            model_name='playerinteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Zespół w którym występuje:'),
        ),
    ]
